import React from "react";
import { Link } from "react-router-dom";
import Footer from "./Footer";
function CorporateHistory()
{
    return(
        <div id="front">
        <h1 style={{"color":"white"}}>Corporate History.</h1>
        <img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/slider_0/sliderchilditems/slideritem_0/image/MQ7-0-image-20190114140623/classic_historie_geschichte_titel_3400x1440.jpeg" height="400px" width="100%" />
        <h1 style={{"color":"white"}}>How it all Began 1834: Gottlieb Daimler.</h1>
        <p style={{"color":"lightpink","fontWeight":"bold"}}>'It's not the idea, it's the implementation that counts.'</p>
        <p style={{"color":"white"}}>Gottlieb Daimler is born on 17 March 1834 in Schorndorf. After training as a gunsmith and working in France, he attends the Polytechnic School in Stuttgart from 1857 to 1859. After completing various technical activities in France and England, he starts work as a draftsman in Geislingen in 1862. At the end of 1863, he is appointed workshop inspector in a machine tool factory in Reutlingen, where he meets Wilhelm Maybach in 1865. In 1872, he becomes Technical Director of the gas engine manufacturer Deutz Gasmotorenfabrik, where he becomes familiar with Otto's four-stroke technology. After differences with the Managing Director, he leaves the company in 1882. Daimler sets up a development workshop in his greenhouse at his Cannstatt villa to concentrate on developing petrol-driven four-stroke engines. Working with Wilhelm Maybach in 1884, he develops an internal combustion engine known today as the 'Grandfather Clock'. With its compact, low-weight design, the machine forms the basis for installation in a vehicle. The costs of trial operations soon consume Daimler's entire fortune, however, so he is obliged to find business partners. He founds 'Daimler-Motoren-Gesellschaft' on 28 November 1890 together with Max Duttenhofer and his business partner Wilhelm Lorenz. But while Duttenhofer wants to produce stationary engines, Daimler prefers to focus on vehicle production, and a dispute ensues.</p>
        <p style={{"color":"white"}}>After Wilhelm Maybach resigns in 1891 due to unacceptable terms of contract, Daimler resorts to a ruse. He continues to build engines with Maybach, but the patents are all in his name. The increasingly tense relationship with Duttenhofer and Lorenz lead them to exclude Daimler as a shareholder. A deterioration in finances leads to stagnating technical development, which prompts DMG to attempt to reinstate Maybach in 1895. He refuses, pointing out that he would not come back without Daimler. In the end, commercial pressures result in both of them returning to the company. Thanks to the Phoenix engine built by Maybach, the Daimler engine gains popularity abroad. A group of English industrialists are prepared to pay 350,000 Marks for licensing rights. Maybach is appointed Technical Director of DMG, and Gottlieb Daimler receives a position on the Technical Board and becomes the Inspector General of the Supervisory Board. The return of both men to DMG is an unexpected boost for the company. Gottlieb Daimler enjoys this rapid development for only a short period of time. He dies of heart disease on 6 March 1900.</p>

        <img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/slider_4/sliderchilditems/slideritem_0/image/MQ7-0-image-20190114140623/classic_historie_geschichte_1884_gottliebdaimler_3400x1440.jpeg" height="400px" width="100%" />
        <h1 style={{"color":"white"}}>How it all Began 1844: Carl Benz.</h1>
         <p style={{"color":"lightpink","fontWeight":"bold"}}>'Love of invention will never die.'</p>
<p style={{"color":"white"}}>Carl Benz is born in Karlsruhe on 25 November 1844. His father dies in July 1846. Despite living on limited financial means, his mother ensures that her son attends a grammar school and later studies mechanical engineering. The young engineer advances quickly from a locksmith to a designer and workshop foreman. In 1871, Carl Benz joins forces with 'mechanician' August Ritter to found his first company, 'Carl Benz and August Ritter, Engineering Workshop', in Mannheim. When Ritter emerges as an unreliable partner, Carl Benz is forced to pay him off using the dowry of his wife, Bertha Ringer, and runs the company alone. From 1878, Carl Benz works intensively on a gas-driven two-stroke engine to realise his vision of a 'vehicle without horses'. After long and laborious attempts, he gets the engine running for the first time on New Year's Eve in 1879. He founds the 'Gasmotorenfabrik Mannheim' (Mannheim Gas Engine Factory) as a shareholding company in October 1882. Benz's share in the company amounts to a mere 5 per cent, however, and he has only limited influence in technical areas. His backers are primarily concerned with the safe business of stationary gas engines.</p>
<p style={{"color":"white"}}>Benz leaves the company in January 1883 and joins forces with new business partners Max Rose and Friedrich Wilhelm Esslinger. They found the company 'Benz & Cie. Rheinische Gasmotoren-Fabrik Mannheim' Benz & Co. Rhine Gas Engine Factory Mannheim' and launch the two-stroke 'System Benz' engine. While Benz strives to implement his automotive vision, his business partners Rose and Esslinger are sceptical of the outcome. Carl Benz is once again faced with finding new investors. Julius Ganss and Friedrich von Fischer replace Rose and Esslinger in May 1890. The combined business model of producing stationary and vehicle engines is a success. But Benz wanted to focus exclusively on vehicles and starts the company 'Carl Benz Söhne' (Carl Benz & Sons) in Ladenburg in 1906. In 1912, Carl Benz resigns as Managing Director and transfers sole management control to his sons. He witnesses the rise of motorisation and the implementation of his ideas. On his 80th birthday, the 'once ridiculed and misunderstood inventor,' as he has been seen in the past, enjoys plaudits from around the world. In his last years (1926 to 1929), Carl Benz remains active as a Board Member of the new Daimler-Benz AG company. The automobile pioneer dies at his home in Ladenburg on 4 April 1929.</p>

<img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/slider_6/sliderchilditems/slideritem_0/image/MQ7-0-image-20190114140623/classic_historie_geschichte_1844_carlbenz_3400x1440.jpeg" height="400px" width="100%" />
<h1 style={{"color":"white"}}>How it all Began 1846: Wilhelm Maybach.</h1>
    <p style={{"color":"lightpink","fontWeight":"bold"}}>The king of designers.</p>
<p style={{"color":"white"}}>Wilhelm Maybach is born in Heilbronn on 9 February 1846 as the son of a master joiner. Orphaned at ten years old following the death of both parents within three years of each another, Wilhelm is adopted into the Reutlinger Bruderhaus in 1856 after friends of the family print an announcement in the 'Stuttgarter Anzeiger' newspaper. It is during his schooling at the Bruderhaus that Wilhelm Maybach first becomes acquainted with Gottlieb Daimler whilst working in the machine shop in 1864. Their close relationship will endure throughout their lives. Wilhelm Maybach initially follows Daimler to Karlsruhe and then in 1872 to the engine manufacturer Deutz. Following a brief stint employed as a draughtsman, he is appointed head designer in January 1873. When Gottlieb Daimler leaves the Deutz Gasmotorenfabrik following internal wranglings, Wilhelm Maybach joins his friend in Cannstatt in October 1882. Here they collaborate in the development of a lightweight, high-speed combustion engine. Daimler-Motoren-Gesellschaft (DMG) is founded in November 1890 by Daimler and two business partners, Max Duttenhofer and Wilhelm Lorenz. Although Wilhelm Maybach was in line to assume the position of head designer, he is unhappy with contractual terms and leaves DMG in February 1891. What follows is a remarkable temporary solution. Secretly funded by Daimler, Maybach continues to improve his mobility concept.</p>
<p style={{"color":"white"}}>Working with a small team in the Hotel Hermann in Cannstatt, he develops significant design concepts, including the belt drive, the Phoenix engine and the spray nozzle carburettor-inspirations that are used in the automobile industry for decades to come. Gottlieb Daimler and Wilhelm Maybach are reinstated at DMG in November 1895 at the behest of English industrialist Frederick Simms, who negotiates a substantial licensing business with the company. Maybach's primary objective is to re-establish DMG's competitive capacity through technical innovation and reliable products. Extensive development work is implemented to advance the concepts devised in the Hotel Hermann to series production status. The most significant outcome is the belt-driven car, the first automobile to be produced by DMG in considerable quantity. Following the death of Max von Duttenhofer in August 1903, Maybach's standing within the company gradually deteriorates, leading to his eventual resignation from DMG in April 1907. Embittered by his treatment, Maybach goes into business with his sons constructing the now legendary vehicles bearing his own name. Wilhelm Maybach dies in Cannstatt on 29 December 1929 at the age of 83.</p>

<img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/paragraph_13/paragraph-left/paragraphimage/image/MQ6-10-image-20190114140616/classic_historie_geschichte_1885_reitwagen_2560x1800.jpeg" height="500px" width="100%" /><br/><br/>

<img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/paragraph_14/paragraph-right/paragraphimage/image/MQ6-10-image-20190114140613/classic_historie_geschichte_1886_motorwagen_2560x2560.jpeg" height="500px" width="100%" /><br/><br/>

<img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/paragraph_19/paragraph-left/paragraphimage/image/MQ6-10-image-20190114140618/classic_historie_geschichte_stern_2560x2000.jpeg" height="500px" width="100%" />

<h1 style={{"color":"white"}}>How it all Began 1909: The three-pointed star on all routes.</h1>
<p style={{"color":"white"}}>From September 1902 DMG holds the patent for successful “Mercedes” brand name. All that is missing is a characteristic trademark. That's when the sons of Gottlieb Daimler, Paul and Adolf, remember, that their father previously used a star for a symbol. The DMG Board of Management follows this inspiration and in June 1909 registers both a three-pointed and four-pointed star as trademarks. Both logos are legally protected but it is the three-pointed star that is ultimately used and a three-dimensional star adorns the front radiator of vehicles from 1910 onwards. With the merging of both companies in June 1926, a new brand name is created, which combines the essential elements of the previous emblems.</p>
<br/><br/>
<h1 style={{"color":"white"}}>How it all Began 1926: Daimler-Benz AG.</h1>
<p style={{"color":"lightpink","fontWeight":"bold"}}>The merger.</p>
<p style={{"color":"white"}}>The period after World War I is badly affected by inflation and poor sales figures-especially for luxury goods such as passenger cars. Only strong brands marketed by financially stable companies are able to survive. Businesses are often forced into mergers or partnerships. Competitors for many years, DMG and Benz & Cie. enter into a joint venture in May 1924. They focus on remaining competitive through coordinated designs, production techniques, purchasing strategies, sales and advertising. The joint marketing activities of the “Mercedes” and “Benz” brands are initially handled by the newly founded “Mercedes-Benz Automobil GmbH”. The fusion of the two oldest automotive manufacturers in the world takes place in June 1926 when Daimler-Benz AG is established. The new company presents the first Daimler-Benz product range as early as October at the 1926 Berlin Motor Show. The exhibition sees the unveiling of the first jointly developed passenger car models launched under the new Mercedes-Benz brand name: The 8/38 hp two-litre car (W 02) and the 12/55 hp three-litre model (W 03).</p>

<img src="https://www.mercedes-benz.com/en/innovation/milestones/corporate-history/_jcr_content/root/paragraph_20/paragraph-right/paragraphimage/image/MQ6-10-image-20190114140622/classic_historie_geschichte_1901_erstermercedes_2560x2000.jpeg" width="100%" height="500px" /><br/><br/>
<p style={{"color":"white"}}>The model 'K' is also on display. Based on the 12/100/140 hp vehicle, this special model features a shorter wheelbase and is the fastest touring car in the world. It is added to the standard sales range in April 1927. The new models bear the new trademark-the Mercedes Star. The three-pointed star graces Mercedes-Benz vehicles to this day. It has become a global symbol of quality and safety. And the Mercedes-Benz name is universally associated with tradition, innovation-and the future of the motor car.</p>

<div id="back">
    <Link id="white" to="/AboutUs">Back to History </Link><br/><br/>
     </div>
     <Footer></Footer>
        </div>
    )
}

export default CorporateHistory;